extends SceneTree
var failures: int = 0
var checks: int = 0
func _initialize() -> void:
	call_deferred("run")
func frames(count: int) -> void:
	for frame in range(count):
		await physics_frame
		await process_frame
func check(condition: bool, description: String) -> void:
	checks += 1
	if condition:
		print("PASS: ", description)
	else:
		failures += 1
		push_error("FAIL: " + description)
func action_event(action: String, pressed: bool) -> void:
	var event := InputEventAction.new()
	event.action = action
	event.pressed = pressed
	Input.parse_input_event(event)
func run() -> void:
	var state := root.get_node("GameState")
	state.reset_run()
	var game = load("res://game.tscn").instantiate()
	root.add_child(game)
	await frames(5)
	check(state.room_index == 0 and game.player.is_on_floor(), "starts in room 1 on entrance floor")
	game.player.position = Vector2(1390, 740)
	await frames(6)
	check(state.room_index == 1, "room 1 exit loads room 2")
	check(game.player.position.x > 100 and game.player.position.x < 200, "destination entrance is outside exit trigger")
	await frames(10)
	check(state.room_index == 1, "transition does not bounce back")
	check(not game.room.has_node("Key"), "junction does not contain the branch-room key")
	game.player.position = Vector2(45, 740)
	await frames(6)
	check(state.room_index == 0 and game.player.position.x > 1200, "junction left exit returns to room 1")
	game.player.position = Vector2(1390, 740)
	await frames(6)
	game.player.position = Vector2(1390, 740)
	await frames(6)
	check(state.room_index == 2, "room 2 exit loads room 3")
	game.player.position = Vector2(1270, 740)
	await frames(4)
	action_event("interact", true)
	await frames(2)
	action_event("interact", false)
	check(state.room_index == 2 and not state.door_unlocked, "door rejects interact without key")
	check(game.get_node("HUD/Message").text.begins_with("SEALED"), "locked door gives visible feedback")
	game.player.position = Vector2(45, 740)
	await frames(6)
	check(state.room_index == 1 and game.player.position.x > 1200, "backtracking selects Return spawn")
	game.player.position = Vector2(730, 790)
	await frames(6)
	check(state.room_index == 4, "junction down exit loads the Lantern Well")
	await frames(30)
	check(state.room_index == 4 and game.player.is_on_floor() and absf(game.player.position.y - 250) < 2, "well arrival lands on top ledge without triggering up exit")
	game.player.position = Vector2(1030, 740)
	await frames(5)
	check(state.has_key and not game.room.has_node("Key"), "key overlap stores state and removes key")
	action_event("restart", true)
	await frames(6)
	action_event("restart", false)
	check(state.room_index == 4 and state.has_key and not game.room.has_node("Key"), "well retry preserves the key and uses the top entrance")
	game.player.position = Vector2(800, 150)
	await frames(6)
	check(state.room_index == 1 and game.current_spawn == &"FromWell", "well up exit selects the junction FromWell spawn")
	await frames(30)
	check(state.room_index == 1 and game.player.is_on_floor() and absf(game.player.position.x - 860) < 2, "return spawn stands beside the opening without bouncing down")
	game.player.health.take_damage(99)
	await frames(55)
	check(state.room_index == 1 and game.current_spawn == &"FromWell" and absf(game.player.position.x - 860) < 2, "death after climbing returns to the correct junction entrance")
	game.player.position = Vector2(730, 790)
	await frames(6)
	check(state.room_index == 4 and not game.room.has_node("Key"), "revisiting lower room does not recreate the collected key")
	game.player.position = Vector2(800, 150)
	await frames(6)
	game.player.position = Vector2(1390, 740)
	await frames(6)
	check(state.room_index == 2 and state.has_key, "key persists after room unload")
	game.player.position = Vector2(1270, 740)
	await frames(4)
	action_event("interact", true)
	await frames(5)
	action_event("interact", false)
	check(state.room_index == 3 and state.door_unlocked, "door accepts key and enters arena")
	check(game.room.get_node("Exits").get_child_count() == 0, "arena has no escape transition")
	action_event("pause", true)
	await frames(2)
	action_event("pause", false)
	check(paused and game.get_node("HUD/Pause").visible, "pause action displays overlay")
	var paused_position: Vector2 = game.player.position
	Input.action_press("move_right")
	await frames(8)
	Input.action_release("move_right")
	check(game.player.position == paused_position, "pause freezes gameplay")
	action_event("pause", true)
	await frames(2)
	action_event("pause", false)
	check(not paused, "same pause action resumes")
	game.player.health.take_damage(99)
	await frames(55)
	check(not game.player.dead and game.player.health.current_health == 6, "death reloads entrance with restored health")
	check(state.has_key and state.door_unlocked, "death preserves progression")
	print("PROGRESSION: ", checks - failures, "/", checks, " passed")
	quit(1 if failures else 0)
